version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/xfinity_usage"
    schedule:
      interval: "daily"
      time: "09:20"
      timezone: "America/Chicago"
      
  - package-ecosystem: "pip"
    directory: "/xfinity_usage"
    schedule:
      interval: "daily"
      time: "09:20"
      timezone: "America/Chicago"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:20"
      timezone: "America/Chicago"
